"""
Token Wisdom × Zernio — Social Distribution Layer
=================================================

Adapted from the BLANK AF Zernio integration (vault/038). Same engine — a single
API fanning one canonical content object out to 14+ platforms LLMs crawl — but
remapped from streetwear drops to a weekly tech-futures publication + a living
encyclopedia.

WHY THIS EXISTS (the strategic fit, in one breath):
  Token Wisdom's #1 growth blocker is *discovery* — the live ghost.io site is gated
  behind an access code, which kills SEO. The public face is the ungated static
  GitHub Pages corpus. Zernio is how that corpus reaches the surfaces large language
  models cite. TW's content IS the AI-era encyclopedia; its 1,941 hand-defined terms
  are exactly the definitional, evergreen material LLMs quote. Every edition keeps us
  inside the ~30-day AI-citation recency window; every Lexicon term is a permanent
  citation surface. Distribution is the missing half of "corpus-as-product."

  This module is the OFF-SITE complement to the on-site Constellation graph
  (lexicon.py). Constellation deepens engagement for readers already here; Zernio
  pushes term + edition surfaces out to where new readers (and crawlers) are.

This module is ready to wire once ZERNIO_API_KEY is present. Everything below is
executable — content generation runs today against real data/; only the final
network call is mocked until the SDK + key are in place.

Setup:
  1. Add ZERNIO_API_KEY to the environment  (sk_ + 64 hex)
  2. pip install zernio-sdk
  3. Uncomment the Zernio import + the createPost call in publish_everywhere()
  4. Set TW_PUBLIC_BASE to the UNGATED static site (never the gated ghost.io URL)

Data sources (already generated by the site build):
  data/lexicon.json    -> terms, definition history, "travels with", recurrence
  data/all_posts.json  -> editions + essays (title, excerpt, cover, tags, date)
"""

from __future__ import annotations

import html
import json
import os
import re
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Callable, Optional

# from zernio import Zernio          # pip install zernio-sdk
# zernio = Zernio()                  # reads ZERNIO_API_KEY from env

# ── Config ──────────────────────────────────────────────────────────────────

ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"

# CRITICAL: the public, UNGATED corpus — this is the whole point. Every CTA points
# here, not at tokenwisdom.ghost.io (which 302s to /private/ and is uncrawlable).
TW_PUBLIC_BASE = os.environ.get(
    "TW_PUBLIC_BASE", "https://iamkhayyam.github.io/tokenwisdom"
).rstrip("/")

TW_TIMEZONE = os.environ.get("TW_TIMEZONE", "America/Edmonton")

# Token Wisdom is a thought-leadership publication, not a visual streetwear brand.
# Platform order is by AI-citation value AND fit. Visual-first networks (Instagram,
# Pinterest, TikTok) are phase 2 / optional — TW's home is text + audio + long-form.
Platform = str

PLATFORM_PRIORITY: list[dict[str, str]] = [
    {"platform": "linkedin",  "reason": "#2 most-cited domain across ChatGPT/Perplexity/Google AI Mode; long-form thought leadership is TW's native register"},
    {"platform": "youtube",   "reason": "16% of LLM answers cite YouTube; TW already has NotebookLM audio + the A/B podcast pairs — transcripts are crawlable expertise"},
    {"platform": "twitter",   "reason": "Real-time pulse; TW's aphoristic coinages (Constitutional Forcing, Substrate Failure) are made for it. X API billed at cost — set a cap"},
    {"platform": "bluesky",   "reason": "Early-mover AI-indexing advantage; the tech-futures crowd is here"},
    {"platform": "mastodon",  "reason": "Federated, fully crawlable, fediverse overlaps TW's researcher/builder audience"},
    {"platform": "reddit",    "reason": "r/Futurology, r/artificial, r/technology — long-form discussion, high citation weight when authentic"},
    {"platform": "threads",   "reason": "Cross-posts from the Meta ecosystem; conversational reach"},
    {"platform": "instagram", "reason": "PHASE 2 — only with a cover/diagram asset. Edition covers + Lexicon term cards can carry it"},
    {"platform": "pinterest", "reason": "PHASE 2 — long shelf-life visual discovery for term cards / essay covers"},
]

# Tags we never want on social (housekeeping / internal taxonomy)
_TAG_STOPLIST = {"newsletter", "pearls of wisdom", "token wisdom", "members", "paid"}


# ── Canonical content object ────────────────────────────────────────────────
# One shape, source of truth for every piece. The platform formatters below take
# this and emit platform-optimized text.

ContentType = str  # edition | essay | term | definition_evolution | constellation | podcast | zeitgeist


@dataclass
class ContentItem:
    type: ContentType
    headline: str
    body_short: str                 # X / Bluesky / Threads length
    body_medium: str                # IG / Reddit-tldr / Mastodon length
    body_long: str                  # LinkedIn / YouTube / Reddit body
    cta_url: str
    kicker: str = ""                # section label: "Pearls of Wisdom", "A Closer Look", "From the Lexicon"
    dek: str = ""                   # subtitle / one-line summary
    hashtags: list[str] = field(default_factory=list)
    media_urls: list[str] = field(default_factory=list)
    id: Optional[str] = None
    scheduled_for: Optional[str] = None   # ISO timestamp
    timezone: str = TW_TIMEZONE


# ── Platform formatter ──────────────────────────────────────────────────────
# Token Wisdom voice: authoritative but human, intellectually serious, a literary
# streak, dry wit, the occasional mystical wink (🔮) used sparingly. NOT all-caps,
# NOT marketing-speak. The idea is the hero; the curator is the differentiator.

def _tags(item: ContentItem, n: int) -> str:
    return " ".join(item.hashtags[:n])


def format_for_platform(item: ContentItem, platform: Platform) -> dict[str, str]:
    H, dek, S, M, L = item.headline, item.dek, item.body_short, item.body_medium, item.body_long
    url, k = item.cta_url, item.kicker

    formatters: dict[Platform, Callable[[], dict[str, str]]] = {
        # Long-form, thought-leadership. TW's strongest AI-citation surface.
        "linkedin": lambda: {
            "content": f"{H}\n\n{L}\n\n{('Read the full piece → ' + url) if url else ''}\n\n{_tags(item, 8)}".strip(),
        },
        # Aphoristic. The coinage or the sharpest line carries it.
        "twitter": lambda: {
            "content": f"{S}\n\n{url}\n\n{_tags(item, 3)}".strip(),
        },
        "bluesky": lambda: {
            "content": f"{S}\n\n{url}".strip(),  # 300 chars, no hashtag spam
        },
        "mastodon": lambda: {
            "content": f"{S}\n\n{url}\n\n{_tags(item, 4)}".strip(),
        },
        "threads": lambda: {
            "content": f"{M if len(M) <= 480 else S}\n\n{url}".strip(),
        },
        # Authentic voice, no marketing speak. Title = headline.
        "reddit": lambda: {
            "content": f"{L}\n\n— from Token Wisdom: {url}".strip(),
            "title": f"{H}" if not k else f"[{k}] {H}",
        },
        # Long description + title. Transcript-as-crawlable-expertise.
        "youtube": lambda: {
            "content": f"{dek}\n\n{L}\n\nThe full archive (ungated): {url}\n\n{_tags(item, 10)}".strip(),
            "title": H,
        },
        # Visual surfaces — phase 2; require media_urls.
        "instagram": lambda: {
            "content": f"{M}\n\n.\n.\n.\n{_tags(item, 12)}".strip(),
        },
        "pinterest": lambda: {
            "content": M,
            "title": H,
        },
    }
    fn = formatters.get(platform)
    return fn() if fn else {"content": S}


# ── Helpers over the real data ──────────────────────────────────────────────

def _load(name: str) -> object:
    return json.loads((DATA / name).read_text())


def _posts() -> list[dict]:
    d = _load("all_posts.json")
    return d if isinstance(d, list) else d.get("posts", d)  # type: ignore[union-attr]


def _strip(text: str, limit: int = 0) -> str:
    text = html.unescape(re.sub(r"<[^>]+>", "", text or "")).strip()
    text = re.sub(r"\s+", " ", text)
    if limit and len(text) > limit:
        text = text[: limit - 1].rstrip() + "…"
    return text


def _post_url(slug: str) -> str:
    return f"{TW_PUBLIC_BASE}/posts/{slug}.html"


def _term_url(slug: str) -> str:
    return f"{TW_PUBLIC_BASE}/lexicon/{slug}.html"


def _constellation_url(slug: str) -> str:
    return f"{TW_PUBLIC_BASE}/lexicon/constellation.html#{slug}"


def _hashtags_from_tags(tags: list[dict]) -> list[str]:
    out = ["#TokenWisdom"]
    for t in tags or []:
        name = (t.get("name") if isinstance(t, dict) else str(t)) or ""
        if name.lower() in _TAG_STOPLIST or name.startswith("#"):
            continue
        tag = "#" + re.sub(r"[^A-Za-z0-9]", "", name.title())
        if len(tag) > 2 and tag not in out:
            out.append(tag)
        if len(out) >= 6:
            break
    return out


# ── Builders: corpus post -> ContentItem ────────────────────────────────────

def _is_edition(post: dict) -> bool:
    t = (post.get("title") or "").lower()
    return "edition" in t or "pearls of wisdom" in t or "token wisdom" in t and "week" in t


def content_item_from_post(post: dict) -> ContentItem:
    """Turn any edition or essay (from all_posts.json) into a ContentItem."""
    title = _strip(post.get("title", ""))
    slug = post.get("slug", "")
    dek = _strip(post.get("custom_excerpt") or post.get("excerpt") or "", 200)
    body = _strip(post.get("excerpt") or post.get("plaintext") or "", 900)
    edition = _is_edition(post)
    primary = (post.get("tags") or [{}])[0]
    kicker = "Pearls of Wisdom" if edition else (primary.get("name") if isinstance(primary, dict) else "A Closer Look")

    return ContentItem(
        type="edition" if edition else "essay",
        id=slug,
        kicker=kicker,
        headline=title,
        dek=dek,
        body_short=_strip(dek or body, 200),
        body_medium=_strip(dek or body, 480),
        body_long=body,
        hashtags=_hashtags_from_tags(post.get("tags", [])),
        media_urls=[post["feature_image"]] if post.get("feature_image") else [],
        cta_url=_post_url(slug),
        scheduled_for=post.get("published_at"),
    )


# ── Builders: Lexicon term -> ContentItem ───────────────────────────────────
# This is the killer automated feed. ~1,941 evergreen, definitional posts — the
# exact bite-sized, citable material LLMs love. The corpus already wrote them.

def _terms() -> list[dict]:
    return _load("lexicon.json")["terms"]  # type: ignore[index]


def content_item_from_term(term: dict) -> ContentItem:
    """A single 'Term of the Week' card — definition + where to learn more."""
    name = term["name"]
    definition = _strip(term.get("definition", ""), 220)
    cat = term.get("category", "")
    n = term.get("edition_count", 1)
    recur = f" Tracked across {n} editions." if n and n > 1 else ""

    short = f"📖 {name} — {definition}"
    medium = (f"From the Token Wisdom Lexicon\n\n{name} ({cat})\n\n{definition}{recur}\n\n"
              f"A living glossary of the AI era, hand-defined edition by edition.")
    long = (f"THE LESS YOU KNOW — {name}\n\n{definition}\n\n"
            f"Category: {cat}.{recur}\n\n"
            f"This is one of ~1,900 terms in the Token Wisdom Lexicon — a glossary built "
            f"not from a dictionary but from three years of weekly tech-futures writing. "
            f"Each term is defined where it actually appeared, and re-defined as its "
            f"meaning shifted.\n\nFull entry, definition history, and the terms it travels "
            f"with: {_term_url(term['slug'])}")

    return ContentItem(
        type="term",
        id=term["slug"],
        kicker="From the Lexicon",
        headline=f"{name} — the Token Wisdom Lexicon",
        dek=definition,
        body_short=short,
        body_medium=medium,
        body_long=long,
        hashtags=["#TokenWisdom", "#Lexicon", "#AI", "#TechFutures", "#" + re.sub(r"[^A-Za-z0-9]", "", name.title())],
        cta_url=_term_url(term["slug"]),
    )


def content_item_definition_evolution(term: dict) -> ContentItem:
    """TW's headline Lexicon feature: how a term was re-defined over time."""
    name = term["name"]
    hist = term.get("definition_history", [])
    distinct = []
    for h in hist:
        txt = _strip(h.get("text", ""))
        if txt and (not distinct or txt != distinct[-1][1]):
            distinct.append((h.get("date", "")[:7], txt))
    arc = "\n\n".join(f"{d}: {t}" for d, t in distinct[:6]) if distinct else _strip(term.get("definition", ""))
    first, latest = term.get("first", {}), term.get("latest", {})
    span = f"{(first.get('date') or '')[:4]}→{(latest.get('date') or '')[:4]}"

    return ContentItem(
        type="definition_evolution",
        id=term["slug"],
        kicker="From the Lexicon",
        headline=f"How '{name}' changed meaning, {span}",
        dek=f"One term, redefined edition by edition.",
        body_short=f"How we defined “{name}” {span} — the meaning moved. 🔮\n\nThe arc:",
        body_medium=f"“{name}” didn't mean the same thing across {span}. Watch the definition drift:\n\n{arc}",
        body_long=(f"DEFINITION DRIFT — {name} ({span})\n\nThe Token Wisdom Lexicon keeps every "
                   f"definition a term has ever had, because the meanings move. Here is how "
                   f"“{name}” evolved:\n\n{arc}\n\nFull arc + sparkline: {_term_url(term['slug'])}"),
        hashtags=["#TokenWisdom", "#Lexicon", "#AI", "#TechFutures"],
        cta_url=_term_url(term["slug"]),
    )


def content_item_constellation_spotlight(term: dict) -> ContentItem:
    """A term + its 'travels with' cluster, pointing at the live graph."""
    name = term["name"]
    related = term.get("related", [])[:5]
    neighbours = ", ".join(r["name"] for r in related) if related else ""
    return ContentItem(
        type="constellation",
        id=term["slug"],
        kicker="The Constellation",
        headline=f"{name} and the ideas it travels with",
        dek=neighbours,
        body_short=f"In Token Wisdom, “{name}” keeps company with: {neighbours}. ✦\n\nSee the map:",
        body_medium=(f"Ideas cluster. In three years of Token Wisdom, “{name}” co-occurs most with:\n\n"
                     f"{neighbours}\n\nExplore the full constellation of the AI era:"),
        body_long=(f"THE CONSTELLATION — {name}\n\nThe Token Wisdom Lexicon isn't a flat list — its "
                   f"terms form a graph. “{name}” sits next to {neighbours}, because they keep "
                   f"showing up in the same weekly editions.\n\nWander the live force-directed map "
                   f"of 200+ recurring ideas: {_constellation_url(term['slug'])}"),
        hashtags=["#TokenWisdom", "#KnowledgeGraph", "#AI", "#TechFutures"],
        cta_url=_constellation_url(term["slug"]),
    )


# ── Term-of-the-week rotation (the automated daily/weekly engine) ───────────
# Deterministic pick so the same day always yields the same term (idempotent
# scheduling). Prefers recurring terms — they're the most citation-worthy.

def term_of_the_week(when: Optional[datetime] = None, min_editions: int = 3) -> ContentItem:
    when = when or datetime.now(timezone.utc)
    pool = [t for t in _terms() if t.get("edition_count", 0) >= min_editions]
    if not pool:
        pool = _terms()
    pool.sort(key=lambda t: t["slug"])
    idx = when.toordinal() % len(pool)
    return content_item_from_term(pool[idx])


# ── Edition release sequence (analog to BLANK AF's drop sequence) ───────────
# A weekly edition becomes a small coordinated arc instead of a single post.

def build_edition_sequence(post: dict) -> list[ContentItem]:
    base = content_item_from_post(post)
    published = post.get("published_at") or datetime.now(timezone.utc).isoformat()
    try:
        dt = datetime.fromisoformat(published.replace("Z", "+00:00"))
    except ValueError:
        dt = datetime.now(timezone.utc)

    teaser = ContentItem(
        type="edition",
        id=f"{base.id}-teaser",
        kicker=base.kicker,
        headline=f"New this week: {base.headline}",
        dek=base.dek,
        body_short=f"This week in Token Wisdom: {base.dek} 🔮",
        body_medium=f"Dropping this week — {base.headline}\n\n{base.dek}",
        body_long=f"{base.headline} lands this week.\n\n{base.dek}\n\nThe Newsletter of Record for the Future of Now.",
        hashtags=base.hashtags,
        media_urls=base.media_urls,
        cta_url=base.cta_url,
        scheduled_for=(dt - timedelta(days=1)).isoformat(),
    )
    base.scheduled_for = dt.isoformat()
    # "The Essay, Aloud" — the podcast / NotebookLM companion, a day later.
    aloud = ContentItem(
        type="podcast",
        id=f"{base.id}-aloud",
        kicker="The Essay, Aloud",
        headline=f"{base.headline} — read aloud",
        dek="Prefer to listen? The audio companion is up.",
        body_short=f"🎧 {base.headline} — now in audio. {base.cta_url}",
        body_medium=f"The audio companion to {base.headline} is live. 🎧\n\n{base.dek}",
        body_long=f"Listen to {base.headline}.\n\n{base.dek}\n\nFull archive (ungated): {base.cta_url}",
        hashtags=base.hashtags + ["#Podcast"],
        cta_url=base.cta_url,
        scheduled_for=(dt + timedelta(days=1)).isoformat(),
    )
    return [teaser, base, aloud]


# ── Publisher ───────────────────────────────────────────────────────────────

def publish_everywhere(item: ContentItem, account_map: dict[str, str]) -> list[dict]:
    """Fan one ContentItem out to every connected account. Mocked until wired."""
    results: list[dict] = []
    for platform, account_id in account_map.items():
        if not account_id:
            continue
        formatted = format_for_platform(item, platform)

        # ── Uncomment when zernio-sdk is installed and ZERNIO_API_KEY is set ──
        # post = zernio.posts.create_post(
        #     content=formatted["content"],
        #     title=formatted.get("title", ""),
        #     scheduled_for=item.scheduled_for,
        #     timezone=item.timezone,
        #     platforms=[{"platform": platform, "account_id": account_id}],
        #     media_urls=",".join(item.media_urls) if item.media_urls else None,
        # )
        # results.append({"platform": platform, "post_id": post["_id"]})

        # Stub until wired:
        preview = formatted["content"].replace("\n", " ")[:90]
        print(f"[zernio] would post -> {platform:9} | {item.type:20} | {preview}")
        results.append({"platform": platform, "post_id": f"stub_{platform}_{item.id}"})
    return results


def account_map_from_env() -> dict[str, str]:
    """Populate the account map from ZERNIO_ACC_<PLATFORM> env vars."""
    out: dict[str, str] = {}
    for p in (x["platform"] for x in PLATFORM_PRIORITY):
        acc = os.environ.get(f"ZERNIO_ACC_{p.upper()}")
        if acc:
            out[p] = acc
    return out


def is_enabled() -> bool:
    """True only when a key AND at least one connected account are present.
    Content generation runs regardless; this gates real network posting."""
    return bool(os.environ.get("ZERNIO_API_KEY")) and bool(account_map_from_env())


# ── Build-pipeline trigger ───────────────────────────────────────────────────
# Called from generate_site.py after a build. Detects posts not seen in a previous
# build and distributes them: editions get the 3-post release arc, essays get a
# single cross-post. State lives in data/.zernio_state.json.
#
# First run (no state) SEEDS silently — it records the existing backlog as
# already-distributed so we never blast 250+ historical editions. Only genuinely
# new slugs on subsequent builds fire.

STATE_FILE = DATA / ".zernio_state.json"


def _load_state() -> dict:
    if STATE_FILE.exists():
        try:
            return json.loads(STATE_FILE.read_text())
        except (json.JSONDecodeError, OSError):
            pass
    return {}


def _save_state(state: dict) -> None:
    STATE_FILE.write_text(json.dumps(state, indent=1))


def sync_new_publications(posts: list[dict]) -> list[str]:
    """Distribute posts whose slugs we haven't published before.

    Returns the list of slugs handled this run. Safe to call on every build:
    first run seeds and fires nothing; later runs fire only new slugs. When
    not is_enabled(), it dry-runs (prints) and still records state so the
    backlog doesn't pile up for the eventual first real send.
    """
    state = _load_state()
    seen: set[str] = set(state.get("published", []))
    current = [(p.get("slug") or "") for p in posts if p.get("slug") and p.get("published_at")]

    # First run: seed the backlog as already-distributed, fire nothing.
    if "published" not in state:
        _save_state({"published": sorted(set(current))})
        print(f"[zernio] seeded distribution state with {len(current)} existing posts (no posts sent)")
        return []

    accounts = account_map_from_env()
    enabled = is_enabled()
    by_slug = {p.get("slug"): p for p in posts}
    new_slugs = [s for s in current if s not in seen]

    if not new_slugs:
        print("[zernio] no new posts to distribute")
        return []

    mode = "LIVE" if enabled else "dry-run (no ZERNIO_API_KEY / accounts)"
    print(f"[zernio] {len(new_slugs)} new post(s) to distribute — {mode}")
    for slug in new_slugs:
        post = by_slug[slug]
        items = build_edition_sequence(post) if _is_edition(post) else [content_item_from_post(post)]
        for item in items:
            if enabled:
                publish_everywhere(item, accounts)
            else:
                fmt = format_for_platform(item, "twitter")["content"].replace("\n", " ")[:90]
                print(f"[zernio]   would distribute [{item.type}] {fmt}")
        seen.add(slug)

    _save_state({"published": sorted(seen)})
    return new_slugs


def post_term_of_the_week(when: Optional[datetime] = None) -> list[dict]:
    """Cron entry point. Publishes the Term of the Week (or dry-runs if not wired)."""
    item = term_of_the_week(when)
    accounts = account_map_from_env()
    if is_enabled():
        return publish_everywhere(item, accounts)
    fmt = format_for_platform(item, "twitter")["content"].replace("\n", " ")[:90]
    print(f"[zernio] term-of-the-week dry-run [{item.id}] {fmt}")
    return []


# ── CLI / demo ──────────────────────────────────────────────────────────────
# Runs today, no key needed — proves the content pipeline end to end against the
# real corpus. `python3 zernio.py`

if __name__ == "__main__":
    import sys

    accounts = account_map_from_env() or {"linkedin": "demo", "twitter": "demo", "bluesky": "demo"}
    cmd = sys.argv[1] if len(sys.argv) > 1 else "term"

    if cmd == "term":
        print("── Term of the week ─────────────────────────────────────────")
        publish_everywhere(term_of_the_week(), accounts)
    elif cmd == "evolution":
        rec = next(t for t in _terms() if t.get("edition_count", 0) >= 10)
        print(f"── Definition drift: {rec['name']} ─────────────────────────")
        publish_everywhere(content_item_definition_evolution(rec), accounts)
    elif cmd == "constellation":
        rec = next(t for t in _terms() if t.get("related"))
        print(f"── Constellation spotlight: {rec['name']} ──────────────────")
        publish_everywhere(content_item_constellation_spotlight(rec), accounts)
    elif cmd == "edition":
        latest = max(_posts(), key=lambda p: p.get("published_at") or "")
        print(f"── Edition sequence: {_strip(latest['title'])} ─────────────")
        for ci in build_edition_sequence(latest):
            print(f"\n[{ci.scheduled_for}] {ci.kicker}")
            publish_everywhere(ci, accounts)
    elif cmd == "totw":
        # Cron entry point — publishes (or dry-runs) the Term of the Week.
        post_term_of_the_week()
    elif cmd == "sync":
        # Distribute any posts not yet seen (seeds silently on first run).
        handled = sync_new_publications(_posts())
        print(f"[zernio] sync handled {len(handled)} new post(s)")
    elif cmd == "status":
        print(f"[zernio] enabled={is_enabled()}  public_base={TW_PUBLIC_BASE}")
        print(f"[zernio] accounts={list(account_map_from_env()) or '(none)'}")
        st = _load_state()
        print(f"[zernio] state: {len(st.get('published', []))} posts recorded")
    else:
        print("usage: python3 zernio.py [term|evolution|constellation|edition|totw|sync|status]")
